from enum import Enum


class States(Enum):
    GREETING = "GREETING"
    GREETING_KNOWN = "GREETING_KNOWN"

    TYPE_OF_WORKOUT = "TYPE_OF_WORKOUT"
    CHOOSE_WORKOUT = "CHOOSE_WORKOUT"
    WORKOUT_BEGIN = "WORKOUT_BEGIN"


    QUESTION = "QUESTION"

    FIRST_EXCERCISE = "FIRST_EXCERCISE"
    NEXT_EXCERCISE = "NEXT_EXCERCISE"
    IN_EXCERCISE = "IN_EXCERCISE"


